import { getCurrentUser } from '@/lib/actions/auth.action';
import { db } from '@/firebase/admin';

export async function GET(request: Request) {
    try {
        const user = await getCurrentUser();
        
        if (!user) {
            return Response.json({
                success: false,
                error: 'Not authenticated'
            }, { status: 401 });
        }

        // Get user's recipes count
        const recipesSnapshot = await db.collection('recipes')
            .where('authorId', '==', user.id)
            .get();
        
        const recipesUploaded = recipesSnapshot.size;

        // Get total likes on user's recipes
        let totalLikes = 0;
        recipesSnapshot.docs.forEach(doc => {
            const data = doc.data();
            totalLikes += data.likes || 0;
        });

        // Get user's bookmarks count
        const bookmarksSnapshot = await db.collection('bookmarks')
            .where('userId', '==', user.id)
            .get();
        
        const totalBookmarks = bookmarksSnapshot.size;

        // Get AI recipes generated by user (recipes with isAIGenerated = true)
        const aiRecipesSnapshot = await db.collection('recipes')
            .where('authorId', '==', user.id)
            .where('isAIGenerated', '==', true)
            .get();
        
        const aiRecipesGenerated = aiRecipesSnapshot.size;

        return Response.json({
            success: true,
            stats: {
                recipesUploaded,
                totalLikes,
                totalBookmarks,
                aiRecipesGenerated
            }
        }, { status: 200 });

    } catch (error) {
        console.error('Error fetching profile stats:', error);
        return Response.json({
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error'
        }, { status: 500 });
    }
}
